esphome:
  name: esp_32cam_1
  platform: ESP32
  board: esp32dev
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
#  use_address: $deviceip

api:

logger:

ota:

esp32_camera:
  name: esp_32cam_1
  #
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  max_framerate: 5 fps
  resolution: 160x120
  jpeg_quality: 10
  idle_framerate: 0.05 fps
  #