esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  use_address: $deviceip

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: $shortname Button
    on_press: 
      then:
        - switch.toggle: relay
        - if:
            condition:
              - switch.is_on: relay
            then:
              - light.turn_on: sonoff_led
            else:
              - light.turn_off: sonoff_led

switch:
  - platform: gpio
    name: $shortname Relay
    pin: GPIO12
    id: relay

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    id: sonoff_led
    name: $shortname LED
    output: basic_green_led
